# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sched.ui'
#
# Created: Fri Oct  7 19:00:06 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Schedule(object):
    def setupUi(self, Schedule):
        Schedule.setObjectName("Schedule")
        Schedule.resize(873, 589)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Schedule.sizePolicy().hasHeightForWidth())
        Schedule.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        Schedule.setFont(font)
        self.schedulesTab = QtGui.QTabWidget(Schedule)
        self.schedulesTab.setGeometry(QtCore.QRect(10, 10, 851, 571))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schedulesTab.sizePolicy().hasHeightForWidth())
        self.schedulesTab.setSizePolicy(sizePolicy)
        self.schedulesTab.setObjectName("schedulesTab")
        self.tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtGui.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 851, 531))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridLayoutWidget.sizePolicy().hasHeightForWidth())
        self.gridLayoutWidget.setSizePolicy(sizePolicy)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.startTime = QtGui.QTimeEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startTime.sizePolicy().hasHeightForWidth())
        self.startTime.setSizePolicy(sizePolicy)
        self.startTime.setObjectName("startTime")
        self.gridLayout.addWidget(self.startTime, 1, 1, 1, 1)
        self.endTime = QtGui.QTimeEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endTime.sizePolicy().hasHeightForWidth())
        self.endTime.setSizePolicy(sizePolicy)
        self.endTime.setObjectName("endTime")
        self.gridLayout.addWidget(self.endTime, 1, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mDay = QtGui.QCheckBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mDay.sizePolicy().hasHeightForWidth())
        self.mDay.setSizePolicy(sizePolicy)
        self.mDay.setObjectName("mDay")
        self.horizontalLayout_3.addWidget(self.mDay)
        self.tDay = QtGui.QCheckBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tDay.sizePolicy().hasHeightForWidth())
        self.tDay.setSizePolicy(sizePolicy)
        self.tDay.setObjectName("tDay")
        self.horizontalLayout_3.addWidget(self.tDay)
        self.wDay = QtGui.QCheckBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wDay.sizePolicy().hasHeightForWidth())
        self.wDay.setSizePolicy(sizePolicy)
        self.wDay.setObjectName("wDay")
        self.horizontalLayout_3.addWidget(self.wDay)
        self.rDay = QtGui.QCheckBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rDay.sizePolicy().hasHeightForWidth())
        self.rDay.setSizePolicy(sizePolicy)
        self.rDay.setObjectName("rDay")
        self.horizontalLayout_3.addWidget(self.rDay)
        self.fDay = QtGui.QCheckBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fDay.sizePolicy().hasHeightForWidth())
        self.fDay.setSizePolicy(sizePolicy)
        self.fDay.setObjectName("fDay")
        self.horizontalLayout_3.addWidget(self.fDay)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 3, 1, 1)
        self.classSelector = QtGui.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classSelector.sizePolicy().hasHeightForWidth())
        self.classSelector.setSizePolicy(sizePolicy)
        self.classSelector.setObjectName("classSelector")
        self.gridLayout.addWidget(self.classSelector, 1, 0, 1, 1)
        self.scheduleList = QtGui.QListWidget(self.gridLayoutWidget)
        self.scheduleList.setObjectName("scheduleList")
        self.gridLayout.addWidget(self.scheduleList, 3, 0, 1, 4)
        self.addToScheduleBtn = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addToScheduleBtn.sizePolicy().hasHeightForWidth())
        self.addToScheduleBtn.setSizePolicy(sizePolicy)
        self.addToScheduleBtn.setObjectName("addToScheduleBtn")
        self.gridLayout.addWidget(self.addToScheduleBtn, 2, 1, 1, 1)
        self.removeFromSchedBtn = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeFromSchedBtn.sizePolicy().hasHeightForWidth())
        self.removeFromSchedBtn.setSizePolicy(sizePolicy)
        self.removeFromSchedBtn.setObjectName("removeFromSchedBtn")
        self.gridLayout.addWidget(self.removeFromSchedBtn, 2, 2, 1, 1)
        self.generateBtn = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateBtn.sizePolicy().hasHeightForWidth())
        self.generateBtn.setSizePolicy(sizePolicy)
        self.generateBtn.setObjectName("generateBtn")
        self.gridLayout.addWidget(self.generateBtn, 2, 3, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(3, 10)
        self.schedulesTab.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 831, 531))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.courseNameText = QtGui.QTextEdit(self.verticalLayoutWidget)
        self.courseNameText.setObjectName("courseNameText")
        self.verticalLayout_2.addWidget(self.courseNameText)
        self.addClassBtn = QtGui.QPushButton(self.verticalLayoutWidget)
        self.addClassBtn.setObjectName("addClassBtn")
        self.verticalLayout_2.addWidget(self.addClassBtn)
        self.removeBtn = QtGui.QPushButton(self.verticalLayoutWidget)
        self.removeBtn.setObjectName("removeBtn")
        self.verticalLayout_2.addWidget(self.removeBtn)
        self.classList = QtGui.QListWidget(self.verticalLayoutWidget)
        self.classList.setObjectName("classList")
        self.verticalLayout_2.addWidget(self.classList)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(4, 10)
        self.schedulesTab.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 851, 541))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.generatedWeeksCombo = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.generatedWeeksCombo.setObjectName("generatedWeeksCombo")
        self.verticalLayout.addWidget(self.generatedWeeksCombo)
        self.generatedTable = QtGui.QTableWidget(self.verticalLayoutWidget_2)
        self.generatedTable.setObjectName("generatedTable")
        self.generatedTable.setColumnCount(0)
        self.generatedTable.setRowCount(0)
        self.verticalLayout.addWidget(self.generatedTable)
        self.schedulesTab.addTab(self.tab_3, "")

        self.retranslateUi(Schedule)
        self.schedulesTab.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Schedule)

    def retranslateUi(self, Schedule):
        Schedule.setWindowTitle(QtGui.QApplication.translate("Schedule", "Scheduler", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Schedule", "Days", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Schedule", "Course Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Schedule", "End Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Schedule", "Start Time", None, QtGui.QApplication.UnicodeUTF8))
        self.mDay.setText(QtGui.QApplication.translate("Schedule", "M", None, QtGui.QApplication.UnicodeUTF8))
        self.tDay.setText(QtGui.QApplication.translate("Schedule", "T", None, QtGui.QApplication.UnicodeUTF8))
        self.wDay.setText(QtGui.QApplication.translate("Schedule", "W", None, QtGui.QApplication.UnicodeUTF8))
        self.rDay.setText(QtGui.QApplication.translate("Schedule", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.fDay.setText(QtGui.QApplication.translate("Schedule", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.addToScheduleBtn.setText(QtGui.QApplication.translate("Schedule", "Add Class", None, QtGui.QApplication.UnicodeUTF8))
        self.removeFromSchedBtn.setText(QtGui.QApplication.translate("Schedule", "Remove Class", None, QtGui.QApplication.UnicodeUTF8))
        self.generateBtn.setText(QtGui.QApplication.translate("Schedule", "Generate Schedules", None, QtGui.QApplication.UnicodeUTF8))
        self.schedulesTab.setTabText(self.schedulesTab.indexOf(self.tab), QtGui.QApplication.translate("Schedule", "Schedule", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Schedule", "Course Name", None, QtGui.QApplication.UnicodeUTF8))
        self.addClassBtn.setText(QtGui.QApplication.translate("Schedule", "Add Class", None, QtGui.QApplication.UnicodeUTF8))
        self.removeBtn.setText(QtGui.QApplication.translate("Schedule", "Remove from List", None, QtGui.QApplication.UnicodeUTF8))
        self.schedulesTab.setTabText(self.schedulesTab.indexOf(self.tab_2), QtGui.QApplication.translate("Schedule", "Classes", None, QtGui.QApplication.UnicodeUTF8))
        self.schedulesTab.setTabText(self.schedulesTab.indexOf(self.tab_3), QtGui.QApplication.translate("Schedule", "Generated Schedules", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Schedule = QtGui.QWidget()
    ui = Ui_Schedule()
    ui.setupUi(Schedule)
    Schedule.show()
    sys.exit(app.exec_())

